import { StyleSheet } from "react-native";
import { FontSize, Color, FontFamily, Padding } from "./GlobalStyles";

export const styles = StyleSheet.create({
    rapunzelxuantrangmailcomLayout: {
        width: 323,
        marginLeft: -161.5,
    },
    textFlexBox: {
        textAlign: "center",
        color: Color.colorBlack,
    },
    iconPosition1: {
        height: 25,
        width: 25,
        marginLeft: -12.5,
        left: "50%",
        position: "absolute",
        overflow: "hidden",
    },
    iconPosition: {
        height: 30,
        width: 30,
        top: 281,
        left: "50%",
        position: "absolute",
        overflow: "hidden",
    },
    text1FlexBox: {
        justifyContent: "center",
        alignItems: "center",
    },
    iconLayout: {
        height: "100%",
        width: "100%",
    },
    rapunzelxuantrangmailcom: {
        top: 27,
        // fontFamily: FontFamily.h6SemiBold,
        lineHeight: 24,
        fontSize: FontSize.size_base,
        color: Color.colorBlack,
        left: "50%",
        position: "absolute",
        width: 323,
        marginLeft: -161.5,
    },
    text: {
        top: 96,
        // fontFamily: FontFamily.h6SemiBold,
        lineHeight: 24,
        fontSize: FontSize.size_base,
        color: Color.colorBlack,
        left: "50%",
        position: "absolute",
        width: 323,
        marginLeft: -161.5,
    },
    trngIHc: {
        marginLeft: -146.5,
        top: 165,
        width: 294,
        // fontFamily: FontFamily.h6SemiBold,
        lineHeight: 24,
        fontSize: FontSize.size_base,
        color: Color.colorBlack,
        left: "50%",
        position: "absolute",
    },
    envelopeIcon: {
        top: 0,
    },
    phoneAltIcon: {
        top: 69,
        paddingLeft: 2,
    },
    mapMarkerAltIcon: {
        top: 138,
        paddingLeft: 6
    },
    facebookSquareIcon: {
        marginLeft: -27.5,
    },
    instagramIcon: {
        marginLeft: 6.5,
    },
    rapunzelxuantrangmailcomParent: {
        top: 207,
        height: 287,
        left: "50%",
        position: "absolute",
    },
    iconArrowBackIos: {
        top: 46,
        left: 32,
        zIndex: 1,
        position: "absolute",
    },
    linH: {
        marginLeft: -28,
        bottom: 10,
        fontSize: FontSize.size_5xl,
        fontWeight: "500",
        // fontFamily: FontFamily.robotoMedium,
        color: Color.colorWhite,
        textAlign: "left",
        zIndex: 1,
        left: "50%",
        position: "absolute",
    },
    searchBar: {
        marginLeft: -187.5,
        backgroundColor: Color.colorGreen,
        borderStyle: "solid",
        borderColor: Color.colorGreen,
        borderBottomWidth: 1,
        height: 94,
        flexDirection: "row",
        paddingLeft: Padding.p_base,
        paddingTop: Padding.p_3xs,
        paddingRight: Padding.p_5xs,
        paddingBottom: Padding.p_3xs,
        width: 375,
        top: 0,
        position: "absolute",
        left: "50%",
    },
    contactDocumentMangement: {
        backgroundColor: Color.colorWhite,
        flex: 1,
        height: "100%",
        overflow: "hidden",
        width: "100%",
    },
});