import { StyleSheet } from "react-native";
import { Color, FontSize, FontFamily, Padding, Border } from "./GlobalStyles";

export const styles = StyleSheet.create({
    qunMtKhuTypo: {
        fontSize: FontSize.size_xs,
        width: 325,
        // fontFamily: FontFamily.interBold,
        fontWeight: "700",
        alignItems: "center",
    },
    inputprimarydefaultPosition: {
        height: 48,
        width: 325,
        marginLeft: -162.5,
        left: "50%",
        position: "absolute",
    },
    wrapperPosition: {
        paddingBottom: Padding.p_mini,
        paddingLeft: Padding.p_mini,
        borderWidth: 1,
        borderColor: Color.colorDarkslategray,
        borderStyle: "solid",
        paddingTop: Padding.p_mini,
        flexDirection: "row",
        width: 325,
        shadowOpacity: 1,
        elevation: 6,
        shadowRadius: 6,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowColor: "rgba(0, 110, 233, 0.1)",
        borderRadius: Border.br_3xs,
        marginLeft: -162.5,
        left: "50%",
        position: "absolute",
    },
    lockPosition: {
        paddingHorizontal: Padding.p_mini,
        width: 52,
        height: 52,
        borderBottomLeftRadius: Border.br_3xs,
        borderTopLeftRadius: Border.br_3xs,
        top: "50%",
        backgroundColor: Color.colorGreen,
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        overflow: "hidden",
    },
    documan: {
        marginLeft: -96.5,
        top: 168,
        fontSize: 40,
        width: 193,
        color: Color.colorGreen,
        // fontFamily: FontFamily.interBold,
        fontWeight: "700",
        left: "50%",
        textAlign: "center",
    },
    ngDngQun: {
        marginLeft: -122.5,
        top: 234,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "500",
        // fontFamily: FontFamily.interMedium,
        width: 246,
        color: Color.colorDarkgray_100,
        left: "50%",
        textAlign: "center",
        position: "absolute",
    },
    paraprimarycenter: {
        color: Color.colorWhite,
        textAlign: "center",
        fontSize: FontSize.size_xs,
    },
    buttonprimarydefault: {
        top: 497,
        paddingVertical: Padding.p_mini,
        width: 325,
        shadowOpacity: 1,
        elevation: 6,
        shadowRadius: 6,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowColor: "rgba(0, 110, 233, 0.1)",
        backgroundColor: Color.colorGreen,
        borderRadius: Border.br_3xs,
        marginLeft: -162.5,
        left: "50%",
        position: "absolute",
    },
    email: {
        // fontFamily: FontFamily.interRegular,
        color: "black",
        fontSize: FontSize.size_sm,
        marginLeft: 50,
        width: 245,
        height: 20,
    },
    message: {
        marginTop: -24,
        paddingTop: Padding.p_base,
        paddingBottom: 17,
    },
    inputprimarydefault: {
        top: 339,
    },
    lock: {
        marginTop: -23.85,
        paddingBottom: Padding.p_base,
        paddingTop: Padding.p_mini,
        width: 47,
        borderBottomLeftRadius: Border.br_3xs,
        borderTopLeftRadius: Border.br_3xs,
        top: "50%",
    },
    inputprimarydefault1: {
        top: 406,
    },
    qunMtKhu: {
        top: 468,
        textAlign: "right",
        height: 15,
        marginLeft: -162.5,
        fontSize: FontSize.size_xs,
        color: Color.colorGreen,
        left: "50%",
        position: "absolute",
    },
    loginTaskMangement: {
        height: "100%",
        overflow: "hidden",
        width: "100%",
        backgroundColor: Color.colorWhite,
    },
});